import type {Metadata} from "next";
import "./globals.css";
import StoreProvider from "@/lib/store/StoreProvider";
import React from "react";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by creat app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
    return (
        <StoreProvider>
            <html lang="en">
            <body>
            {children}
            </body>
            </html>
        </StoreProvider>
    );
}
